// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForCreateForecastResults implements pgx.CopyFromSource.
type iteratorForCreateForecastResults struct {
	rows                 []CreateForecastResultsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateForecastResults) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateForecastResults) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ScenarioID,
		r.rows[0].Year,
		r.rows[0].P10,
		r.rows[0].P50,
		r.rows[0].P90,
	}, nil
}

func (r iteratorForCreateForecastResults) Err() error {
	return nil
}

// forecast_results --------------------------------------------------------------------
func (q *Queries) CreateForecastResults(ctx context.Context, arg []CreateForecastResultsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"forecast_results"}, []string{"scenario_id", "year", "p10", "p50", "p90"}, &iteratorForCreateForecastResults{rows: arg})
}
