// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BankAccount struct {
	ID   int32
	Name string
}

type BankAccountBalance struct {
	ID              int32
	MonthlyRecordID int32
	BankAccountID   int32
	Amount          int32
}

type BigPurchase struct {
	ID                 int32
	Name               string
	BaseAmount         int32
	BaseDate           pgtype.Date
	CycleYears         int32
	CategoryGrowthRate pgtype.Numeric
	TradeInValue       int32
	Recurring          bool
	FinancingMode      string
}

type ChatMessage struct {
	ID        int32
	SessionID int32
	Role      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

type ChatSession struct {
	ID               int32
	StartedAt        pgtype.Timestamptz
	ContextSummaryID pgtype.Int4
}

type ContextSummary struct {
	ID          int32
	GeneratedAt pgtype.Timestamptz
	ScenarioID  pgtype.Int4
	SummaryJson []byte
}

type ExpenseCategory struct {
	ID              int32
	MonthlyRecordID int32
	Category        string
	Amount          int32
}

type ExpenseForecast struct {
	ID             int32
	FamilyMemberID int32
	Stage          string
	Track          string
	AnnualCost     int32
	StartAge       int32
	EndAge         int32
	IsOverride     bool
}

type FamilyMember struct {
	ID         int32
	Relation   string
	BirthMonth pgtype.Date
}

type ForecastResult struct {
	ID         int32
	ScenarioID int32
	Year       int32
	P10        int32
	P50        int32
	P90        int32
}

type Fund struct {
	ID             int32
	Name           string
	IsinOrCode     pgtype.Text
	NavSourceUrl   pgtype.Text
	NavProxyFundID pgtype.Int4
}

type FundNavHistory struct {
	ID       int32
	FundID   int32
	NavDate  pgtype.Date
	NavPrice int32
}

type Goal struct {
	ID          int32
	GoalType    string
	TargetValue pgtype.Numeric
	TargetDate  pgtype.Date
}

type MonthlyRecord struct {
	ID            int32
	RecordMonth   pgtype.Date
	IncomeMonthly int32
	BankBalance   int32
	CreatedAt     pgtype.Timestamptz
}

type NisaContribution struct {
	ID               int32
	ContributionDate pgtype.Date
	Amount           int32
	FundID           int32
	ContributionType string
}

type Scenario struct {
	ID     int32
	RunAt  pgtype.Timestamptz
	Params []byte
}
