// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type BankAccount struct {
	ID   int64
	Name string
}

type BankAccountBalance struct {
	ID              int64
	MonthlyRecordID int64
	BankAccountID   int64
	Amount          int64
}

type BigPurchase struct {
	ID                 int64
	Name               string
	BaseAmount         int64
	BaseDate           time.Time
	CycleYears         int64
	CategoryGrowthRate sql.NullFloat64
	TradeInValue       int64
	Recurring          bool
	FinancingMode      string
}

type ChatMessage struct {
	ID        int64
	SessionID int64
	Role      string
	Content   string
	CreatedAt time.Time
}

type ChatSession struct {
	ID               int64
	StartedAt        time.Time
	ContextSummaryID sql.NullInt64
}

type ContextSummary struct {
	ID          int64
	GeneratedAt time.Time
	ScenarioID  sql.NullInt64
	SummaryJson string
}

type ExpenseCategory struct {
	ID              int64
	MonthlyRecordID int64
	Category        string
	Amount          int64
}

type ExpenseForecast struct {
	ID             int64
	FamilyMemberID int64
	Stage          string
	Track          string
	AnnualCost     int64
	StartAge       int64
	EndAge         int64
	IsOverride     bool
}

type FamilyMember struct {
	ID         int64
	Relation   string
	BirthMonth time.Time
}

type ForecastResult struct {
	ID         int64
	ScenarioID int64
	Year       int64
	P10        int64
	P50        int64
	P90        int64
}

type Fund struct {
	ID             int64
	Name           string
	IsinOrCode     sql.NullString
	NavSourceUrl   sql.NullString
	NavProxyFundID sql.NullInt64
}

type FundNavHistory struct {
	ID       int64
	FundID   int64
	NavDate  time.Time
	NavPrice int64
}

type Goal struct {
	ID          int64
	GoalType    string
	TargetValue float64
	TargetDate  sql.NullTime
}

type MonthlyRecord struct {
	ID            int64
	RecordMonth   time.Time
	IncomeMonthly int64
	BankBalance   int64
	CreatedAt     time.Time
}

type NisaContribution struct {
	ID               int64
	ContributionDate time.Time
	Amount           int64
	FundID           int64
	ContributionType string
}

type Scenario struct {
	ID     int64
	RunAt  time.Time
	Params string
}
