// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createBankAccount = `-- name: CreateBankAccount :one

INSERT INTO bank_accounts (name)
VALUES (?)
RETURNING id, name
`

// bank_accounts -----------------------------------------------------------------------------
func (q *Queries) CreateBankAccount(ctx context.Context, name string) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, createBankAccount, name)
	var i BankAccount
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createBankAccountBalance = `-- name: CreateBankAccountBalance :one

INSERT INTO bank_account_balances (monthly_record_id, bank_account_id, amount)
VALUES (?, ?, ?)
RETURNING id, monthly_record_id, bank_account_id, amount
`

type CreateBankAccountBalanceParams struct {
	MonthlyRecordID int64
	BankAccountID   int64
	Amount          int64
}

// bank_account_balances -----------------------------------------------------------------------
func (q *Queries) CreateBankAccountBalance(ctx context.Context, arg CreateBankAccountBalanceParams) (BankAccountBalance, error) {
	row := q.db.QueryRowContext(ctx, createBankAccountBalance, arg.MonthlyRecordID, arg.BankAccountID, arg.Amount)
	var i BankAccountBalance
	err := row.Scan(
		&i.ID,
		&i.MonthlyRecordID,
		&i.BankAccountID,
		&i.Amount,
	)
	return i, err
}

const createBigPurchase = `-- name: CreateBigPurchase :one

INSERT INTO big_purchases (name, base_amount, base_date, cycle_years, category_growth_rate, trade_in_value, recurring, financing_mode)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, base_amount, base_date, cycle_years, category_growth_rate, trade_in_value, recurring, financing_mode
`

type CreateBigPurchaseParams struct {
	Name               string
	BaseAmount         int64
	BaseDate           time.Time
	CycleYears         int64
	CategoryGrowthRate sql.NullFloat64
	TradeInValue       int64
	Recurring          bool
	FinancingMode      string
}

// big_purchases --------------------------------------------------------------
func (q *Queries) CreateBigPurchase(ctx context.Context, arg CreateBigPurchaseParams) (BigPurchase, error) {
	row := q.db.QueryRowContext(ctx, createBigPurchase,
		arg.Name,
		arg.BaseAmount,
		arg.BaseDate,
		arg.CycleYears,
		arg.CategoryGrowthRate,
		arg.TradeInValue,
		arg.Recurring,
		arg.FinancingMode,
	)
	var i BigPurchase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseAmount,
		&i.BaseDate,
		&i.CycleYears,
		&i.CategoryGrowthRate,
		&i.TradeInValue,
		&i.Recurring,
		&i.FinancingMode,
	)
	return i, err
}

const createChatMessage = `-- name: CreateChatMessage :one

INSERT INTO chat_messages (session_id, role, content)
VALUES (?, ?, ?)
RETURNING id, session_id, role, content, created_at
`

type CreateChatMessageParams struct {
	SessionID int64
	Role      string
	Content   string
}

// chat_messages -------------------------------------------------------------------------------
func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage, arg.SessionID, arg.Role, arg.Content)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createChatSession = `-- name: CreateChatSession :one

INSERT INTO chat_sessions (context_summary_id)
VALUES (?)
RETURNING id, started_at, context_summary_id
`

// chat_sessions -----------------------------------------------------------------------------
func (q *Queries) CreateChatSession(ctx context.Context, contextSummaryID sql.NullInt64) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, createChatSession, contextSummaryID)
	var i ChatSession
	err := row.Scan(&i.ID, &i.StartedAt, &i.ContextSummaryID)
	return i, err
}

const createContextSummary = `-- name: CreateContextSummary :one

INSERT INTO context_summaries (scenario_id, summary_json)
VALUES (?, ?)
RETURNING id, generated_at, scenario_id, summary_json
`

type CreateContextSummaryParams struct {
	ScenarioID  sql.NullInt64
	SummaryJson string
}

// context_summaries -----------------------------------------------------------------------
func (q *Queries) CreateContextSummary(ctx context.Context, arg CreateContextSummaryParams) (ContextSummary, error) {
	row := q.db.QueryRowContext(ctx, createContextSummary, arg.ScenarioID, arg.SummaryJson)
	var i ContextSummary
	err := row.Scan(
		&i.ID,
		&i.GeneratedAt,
		&i.ScenarioID,
		&i.SummaryJson,
	)
	return i, err
}

const createExpenseCategory = `-- name: CreateExpenseCategory :one

INSERT INTO expense_categories (monthly_record_id, category, amount)
VALUES (?, ?, ?)
RETURNING id, monthly_record_id, category, amount
`

type CreateExpenseCategoryParams struct {
	MonthlyRecordID int64
	Category        string
	Amount          int64
}

// expense_categories ------------------------------------------------------
func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, createExpenseCategory, arg.MonthlyRecordID, arg.Category, arg.Amount)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.MonthlyRecordID,
		&i.Category,
		&i.Amount,
	)
	return i, err
}

const createExpenseForecast = `-- name: CreateExpenseForecast :one

INSERT INTO expense_forecasts (family_member_id, stage, track, annual_cost, start_age, end_age, is_override)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, family_member_id, stage, track, annual_cost, start_age, end_age, is_override
`

type CreateExpenseForecastParams struct {
	FamilyMemberID int64
	Stage          string
	Track          string
	AnnualCost     int64
	StartAge       int64
	EndAge         int64
	IsOverride     bool
}

// expense_forecasts ---------------------------------------------------------
func (q *Queries) CreateExpenseForecast(ctx context.Context, arg CreateExpenseForecastParams) (ExpenseForecast, error) {
	row := q.db.QueryRowContext(ctx, createExpenseForecast,
		arg.FamilyMemberID,
		arg.Stage,
		arg.Track,
		arg.AnnualCost,
		arg.StartAge,
		arg.EndAge,
		arg.IsOverride,
	)
	var i ExpenseForecast
	err := row.Scan(
		&i.ID,
		&i.FamilyMemberID,
		&i.Stage,
		&i.Track,
		&i.AnnualCost,
		&i.StartAge,
		&i.EndAge,
		&i.IsOverride,
	)
	return i, err
}

const createFamilyMember = `-- name: CreateFamilyMember :one

INSERT INTO family_members (relation, birth_month)
VALUES (?, ?)
RETURNING id, relation, birth_month
`

type CreateFamilyMemberParams struct {
	Relation   string
	BirthMonth time.Time
}

// family_members -----------------------------------------------------------
func (q *Queries) CreateFamilyMember(ctx context.Context, arg CreateFamilyMemberParams) (FamilyMember, error) {
	row := q.db.QueryRowContext(ctx, createFamilyMember, arg.Relation, arg.BirthMonth)
	var i FamilyMember
	err := row.Scan(&i.ID, &i.Relation, &i.BirthMonth)
	return i, err
}

const createForecastResult = `-- name: CreateForecastResult :exec

INSERT INTO forecast_results (scenario_id, year, p10, p50, p90)
VALUES (?, ?, ?, ?, ?)
`

type CreateForecastResultParams struct {
	ScenarioID int64
	Year       int64
	P10        int64
	P50        int64
	P90        int64
}

// forecast_results --------------------------------------------------------------------
func (q *Queries) CreateForecastResult(ctx context.Context, arg CreateForecastResultParams) error {
	_, err := q.db.ExecContext(ctx, createForecastResult,
		arg.ScenarioID,
		arg.Year,
		arg.P10,
		arg.P50,
		arg.P90,
	)
	return err
}

const createFund = `-- name: CreateFund :one

INSERT INTO funds (name, isin_or_code, nav_source_url, nav_proxy_fund_id)
VALUES (?, ?, ?, ?)
RETURNING id, name, isin_or_code, nav_source_url, nav_proxy_fund_id
`

type CreateFundParams struct {
	Name           string
	IsinOrCode     sql.NullString
	NavSourceUrl   sql.NullString
	NavProxyFundID sql.NullInt64
}

// funds ------------------------------------------------------------------------
func (q *Queries) CreateFund(ctx context.Context, arg CreateFundParams) (Fund, error) {
	row := q.db.QueryRowContext(ctx, createFund,
		arg.Name,
		arg.IsinOrCode,
		arg.NavSourceUrl,
		arg.NavProxyFundID,
	)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsinOrCode,
		&i.NavSourceUrl,
		&i.NavProxyFundID,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one

INSERT INTO goals (goal_type, target_value, target_date)
VALUES (?, ?, ?)
RETURNING id, goal_type, target_value, target_date
`

type CreateGoalParams struct {
	GoalType    string
	TargetValue float64
	TargetDate  sql.NullTime
}

// goals --------------------------------------------------------------------------
func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal, arg.GoalType, arg.TargetValue, arg.TargetDate)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.GoalType,
		&i.TargetValue,
		&i.TargetDate,
	)
	return i, err
}

const createNisaContribution = `-- name: CreateNisaContribution :one

INSERT INTO nisa_contributions (contribution_date, amount, fund_id, contribution_type)
VALUES (?, ?, ?, ?)
RETURNING id, contribution_date, amount, fund_id, contribution_type
`

type CreateNisaContributionParams struct {
	ContributionDate time.Time
	Amount           int64
	FundID           int64
	ContributionType string
}

// nisa_contributions -----------------------------------------------------------
func (q *Queries) CreateNisaContribution(ctx context.Context, arg CreateNisaContributionParams) (NisaContribution, error) {
	row := q.db.QueryRowContext(ctx, createNisaContribution,
		arg.ContributionDate,
		arg.Amount,
		arg.FundID,
		arg.ContributionType,
	)
	var i NisaContribution
	err := row.Scan(
		&i.ID,
		&i.ContributionDate,
		&i.Amount,
		&i.FundID,
		&i.ContributionType,
	)
	return i, err
}

const createScenario = `-- name: CreateScenario :one

INSERT INTO scenarios (params)
VALUES (?)
RETURNING id, run_at, params
`

// scenarios ------------------------------------------------------------------------
func (q *Queries) CreateScenario(ctx context.Context, params string) (Scenario, error) {
	row := q.db.QueryRowContext(ctx, createScenario, params)
	var i Scenario
	err := row.Scan(&i.ID, &i.RunAt, &i.Params)
	return i, err
}

const deleteBankAccount = `-- name: DeleteBankAccount :exec
DELETE FROM bank_accounts WHERE id = ?
`

func (q *Queries) DeleteBankAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBankAccount, id)
	return err
}

const deleteBankAccountBalancesByMonthlyRecord = `-- name: DeleteBankAccountBalancesByMonthlyRecord :exec
DELETE FROM bank_account_balances WHERE monthly_record_id = ?
`

func (q *Queries) DeleteBankAccountBalancesByMonthlyRecord(ctx context.Context, monthlyRecordID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBankAccountBalancesByMonthlyRecord, monthlyRecordID)
	return err
}

const deleteBigPurchase = `-- name: DeleteBigPurchase :exec
DELETE FROM big_purchases WHERE id = ?
`

func (q *Queries) DeleteBigPurchase(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBigPurchase, id)
	return err
}

const deleteExpenseCategoriesByMonthlyRecord = `-- name: DeleteExpenseCategoriesByMonthlyRecord :exec
DELETE FROM expense_categories WHERE monthly_record_id = ?
`

func (q *Queries) DeleteExpenseCategoriesByMonthlyRecord(ctx context.Context, monthlyRecordID int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpenseCategoriesByMonthlyRecord, monthlyRecordID)
	return err
}

const deleteExpenseForecast = `-- name: DeleteExpenseForecast :exec
DELETE FROM expense_forecasts WHERE id = ?
`

func (q *Queries) DeleteExpenseForecast(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpenseForecast, id)
	return err
}

const deleteFamilyMember = `-- name: DeleteFamilyMember :exec
DELETE FROM family_members WHERE id = ?
`

func (q *Queries) DeleteFamilyMember(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFamilyMember, id)
	return err
}

const deleteFund = `-- name: DeleteFund :exec
DELETE FROM funds WHERE id = ?
`

func (q *Queries) DeleteFund(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFund, id)
	return err
}

const deleteNisaContributionByFundAndDate = `-- name: DeleteNisaContributionByFundAndDate :exec
DELETE FROM nisa_contributions WHERE fund_id = ? AND contribution_date = ?
`

type DeleteNisaContributionByFundAndDateParams struct {
	FundID           int64
	ContributionDate time.Time
}

func (q *Queries) DeleteNisaContributionByFundAndDate(ctx context.Context, arg DeleteNisaContributionByFundAndDateParams) error {
	_, err := q.db.ExecContext(ctx, deleteNisaContributionByFundAndDate, arg.FundID, arg.ContributionDate)
	return err
}

const getBigPurchase = `-- name: GetBigPurchase :one
SELECT id, name, base_amount, base_date, cycle_years, category_growth_rate, trade_in_value, recurring, financing_mode FROM big_purchases WHERE id = ?
`

func (q *Queries) GetBigPurchase(ctx context.Context, id int64) (BigPurchase, error) {
	row := q.db.QueryRowContext(ctx, getBigPurchase, id)
	var i BigPurchase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseAmount,
		&i.BaseDate,
		&i.CycleYears,
		&i.CategoryGrowthRate,
		&i.TradeInValue,
		&i.Recurring,
		&i.FinancingMode,
	)
	return i, err
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, started_at, context_summary_id FROM chat_sessions WHERE id = ?
`

func (q *Queries) GetChatSession(ctx context.Context, id int64) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getChatSession, id)
	var i ChatSession
	err := row.Scan(&i.ID, &i.StartedAt, &i.ContextSummaryID)
	return i, err
}

const getFamilyMember = `-- name: GetFamilyMember :one
SELECT id, relation, birth_month FROM family_members WHERE id = ?
`

func (q *Queries) GetFamilyMember(ctx context.Context, id int64) (FamilyMember, error) {
	row := q.db.QueryRowContext(ctx, getFamilyMember, id)
	var i FamilyMember
	err := row.Scan(&i.ID, &i.Relation, &i.BirthMonth)
	return i, err
}

const getFund = `-- name: GetFund :one
SELECT id, name, isin_or_code, nav_source_url, nav_proxy_fund_id FROM funds WHERE id = ?
`

func (q *Queries) GetFund(ctx context.Context, id int64) (Fund, error) {
	row := q.db.QueryRowContext(ctx, getFund, id)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsinOrCode,
		&i.NavSourceUrl,
		&i.NavProxyFundID,
	)
	return i, err
}

const getLatestBankAccountBalance = `-- name: GetLatestBankAccountBalance :one
SELECT bab.id, bab.monthly_record_id, bab.bank_account_id, bab.amount FROM bank_account_balances bab
JOIN monthly_records mr ON mr.id = bab.monthly_record_id
WHERE bab.bank_account_id = ?
ORDER BY mr.record_month DESC
LIMIT 1
`

func (q *Queries) GetLatestBankAccountBalance(ctx context.Context, bankAccountID int64) (BankAccountBalance, error) {
	row := q.db.QueryRowContext(ctx, getLatestBankAccountBalance, bankAccountID)
	var i BankAccountBalance
	err := row.Scan(
		&i.ID,
		&i.MonthlyRecordID,
		&i.BankAccountID,
		&i.Amount,
	)
	return i, err
}

const getLatestContextSummary = `-- name: GetLatestContextSummary :one
SELECT id, generated_at, scenario_id, summary_json FROM context_summaries ORDER BY generated_at DESC LIMIT 1
`

func (q *Queries) GetLatestContextSummary(ctx context.Context) (ContextSummary, error) {
	row := q.db.QueryRowContext(ctx, getLatestContextSummary)
	var i ContextSummary
	err := row.Scan(
		&i.ID,
		&i.GeneratedAt,
		&i.ScenarioID,
		&i.SummaryJson,
	)
	return i, err
}

const getLatestFundNav = `-- name: GetLatestFundNav :one
SELECT id, fund_id, nav_date, nav_price FROM fund_nav_history WHERE fund_id = ? ORDER BY nav_date DESC LIMIT 1
`

func (q *Queries) GetLatestFundNav(ctx context.Context, fundID int64) (FundNavHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestFundNav, fundID)
	var i FundNavHistory
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.NavDate,
		&i.NavPrice,
	)
	return i, err
}

const getMonthlyRecordByMonth = `-- name: GetMonthlyRecordByMonth :one
SELECT id, record_month, income_monthly, bank_balance, created_at FROM monthly_records WHERE record_month = ?
`

func (q *Queries) GetMonthlyRecordByMonth(ctx context.Context, recordMonth time.Time) (MonthlyRecord, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyRecordByMonth, recordMonth)
	var i MonthlyRecord
	err := row.Scan(
		&i.ID,
		&i.RecordMonth,
		&i.IncomeMonthly,
		&i.BankBalance,
		&i.CreatedAt,
	)
	return i, err
}

const getNisaContributionByFundAndDate = `-- name: GetNisaContributionByFundAndDate :one
SELECT id, contribution_date, amount, fund_id, contribution_type FROM nisa_contributions WHERE fund_id = ? AND contribution_date = ?
`

type GetNisaContributionByFundAndDateParams struct {
	FundID           int64
	ContributionDate time.Time
}

func (q *Queries) GetNisaContributionByFundAndDate(ctx context.Context, arg GetNisaContributionByFundAndDateParams) (NisaContribution, error) {
	row := q.db.QueryRowContext(ctx, getNisaContributionByFundAndDate, arg.FundID, arg.ContributionDate)
	var i NisaContribution
	err := row.Scan(
		&i.ID,
		&i.ContributionDate,
		&i.Amount,
		&i.FundID,
		&i.ContributionType,
	)
	return i, err
}

const getScenario = `-- name: GetScenario :one
SELECT id, run_at, params FROM scenarios WHERE id = ?
`

func (q *Queries) GetScenario(ctx context.Context, id int64) (Scenario, error) {
	row := q.db.QueryRowContext(ctx, getScenario, id)
	var i Scenario
	err := row.Scan(&i.ID, &i.RunAt, &i.Params)
	return i, err
}

const listBankAccountBalancesByMonthlyRecord = `-- name: ListBankAccountBalancesByMonthlyRecord :many
SELECT id, monthly_record_id, bank_account_id, amount FROM bank_account_balances WHERE monthly_record_id = ?
`

func (q *Queries) ListBankAccountBalancesByMonthlyRecord(ctx context.Context, monthlyRecordID int64) ([]BankAccountBalance, error) {
	rows, err := q.db.QueryContext(ctx, listBankAccountBalancesByMonthlyRecord, monthlyRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccountBalance
	for rows.Next() {
		var i BankAccountBalance
		if err := rows.Scan(
			&i.ID,
			&i.MonthlyRecordID,
			&i.BankAccountID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT id, name FROM bank_accounts ORDER BY id
`

func (q *Queries) ListBankAccounts(ctx context.Context) ([]BankAccount, error) {
	rows, err := q.db.QueryContext(ctx, listBankAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBigPurchases = `-- name: ListBigPurchases :many
SELECT id, name, base_amount, base_date, cycle_years, category_growth_rate, trade_in_value, recurring, financing_mode FROM big_purchases ORDER BY base_date
`

func (q *Queries) ListBigPurchases(ctx context.Context) ([]BigPurchase, error) {
	rows, err := q.db.QueryContext(ctx, listBigPurchases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BigPurchase
	for rows.Next() {
		var i BigPurchase
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseAmount,
			&i.BaseDate,
			&i.CycleYears,
			&i.CategoryGrowthRate,
			&i.TradeInValue,
			&i.Recurring,
			&i.FinancingMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessagesBySession = `-- name: ListChatMessagesBySession :many
SELECT id, session_id, role, content, created_at FROM chat_messages WHERE session_id = ? ORDER BY created_at
`

func (q *Queries) ListChatMessagesBySession(ctx context.Context, sessionID int64) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT ec.id, ec.monthly_record_id, ec.category, ec.amount FROM expense_categories ec
JOIN monthly_records mr ON mr.id = ec.monthly_record_id
ORDER BY mr.record_month
`

func (q *Queries) ListExpenseCategories(ctx context.Context) ([]ExpenseCategory, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseCategory
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.MonthlyRecordID,
			&i.Category,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseCategoriesByMonthlyRecord = `-- name: ListExpenseCategoriesByMonthlyRecord :many
SELECT id, monthly_record_id, category, amount FROM expense_categories WHERE monthly_record_id = ? ORDER BY id
`

func (q *Queries) ListExpenseCategoriesByMonthlyRecord(ctx context.Context, monthlyRecordID int64) ([]ExpenseCategory, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseCategoriesByMonthlyRecord, monthlyRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseCategory
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.MonthlyRecordID,
			&i.Category,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseForecasts = `-- name: ListExpenseForecasts :many
SELECT id, family_member_id, stage, track, annual_cost, start_age, end_age, is_override FROM expense_forecasts ORDER BY family_member_id, start_age
`

func (q *Queries) ListExpenseForecasts(ctx context.Context) ([]ExpenseForecast, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseForecasts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseForecast
	for rows.Next() {
		var i ExpenseForecast
		if err := rows.Scan(
			&i.ID,
			&i.FamilyMemberID,
			&i.Stage,
			&i.Track,
			&i.AnnualCost,
			&i.StartAge,
			&i.EndAge,
			&i.IsOverride,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseForecastsByFamilyMember = `-- name: ListExpenseForecastsByFamilyMember :many
SELECT id, family_member_id, stage, track, annual_cost, start_age, end_age, is_override FROM expense_forecasts WHERE family_member_id = ? ORDER BY start_age
`

func (q *Queries) ListExpenseForecastsByFamilyMember(ctx context.Context, familyMemberID int64) ([]ExpenseForecast, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseForecastsByFamilyMember, familyMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseForecast
	for rows.Next() {
		var i ExpenseForecast
		if err := rows.Scan(
			&i.ID,
			&i.FamilyMemberID,
			&i.Stage,
			&i.Track,
			&i.AnnualCost,
			&i.StartAge,
			&i.EndAge,
			&i.IsOverride,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFamilyMembers = `-- name: ListFamilyMembers :many
SELECT id, relation, birth_month FROM family_members ORDER BY birth_month
`

func (q *Queries) ListFamilyMembers(ctx context.Context) ([]FamilyMember, error) {
	rows, err := q.db.QueryContext(ctx, listFamilyMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FamilyMember
	for rows.Next() {
		var i FamilyMember
		if err := rows.Scan(&i.ID, &i.Relation, &i.BirthMonth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForecastResultsByScenario = `-- name: ListForecastResultsByScenario :many
SELECT id, scenario_id, year, p10, p50, p90 FROM forecast_results WHERE scenario_id = ? ORDER BY year
`

func (q *Queries) ListForecastResultsByScenario(ctx context.Context, scenarioID int64) ([]ForecastResult, error) {
	rows, err := q.db.QueryContext(ctx, listForecastResultsByScenario, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForecastResult
	for rows.Next() {
		var i ForecastResult
		if err := rows.Scan(
			&i.ID,
			&i.ScenarioID,
			&i.Year,
			&i.P10,
			&i.P50,
			&i.P90,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFundNavHistory = `-- name: ListFundNavHistory :many
SELECT id, fund_id, nav_date, nav_price FROM fund_nav_history WHERE fund_id = ? ORDER BY nav_date
`

func (q *Queries) ListFundNavHistory(ctx context.Context, fundID int64) ([]FundNavHistory, error) {
	rows, err := q.db.QueryContext(ctx, listFundNavHistory, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FundNavHistory
	for rows.Next() {
		var i FundNavHistory
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.NavDate,
			&i.NavPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFunds = `-- name: ListFunds :many
SELECT id, name, isin_or_code, nav_source_url, nav_proxy_fund_id FROM funds ORDER BY id
`

func (q *Queries) ListFunds(ctx context.Context) ([]Fund, error) {
	rows, err := q.db.QueryContext(ctx, listFunds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fund
	for rows.Next() {
		var i Fund
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsinOrCode,
			&i.NavSourceUrl,
			&i.NavProxyFundID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, goal_type, target_value, target_date FROM goals ORDER BY id
`

func (q *Queries) ListGoals(ctx context.Context) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.GoalType,
			&i.TargetValue,
			&i.TargetDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyRecords = `-- name: ListMonthlyRecords :many
SELECT id, record_month, income_monthly, bank_balance, created_at FROM monthly_records ORDER BY record_month DESC
`

func (q *Queries) ListMonthlyRecords(ctx context.Context) ([]MonthlyRecord, error) {
	rows, err := q.db.QueryContext(ctx, listMonthlyRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyRecord
	for rows.Next() {
		var i MonthlyRecord
		if err := rows.Scan(
			&i.ID,
			&i.RecordMonth,
			&i.IncomeMonthly,
			&i.BankBalance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNisaContributions = `-- name: ListNisaContributions :many
SELECT id, contribution_date, amount, fund_id, contribution_type FROM nisa_contributions ORDER BY contribution_date
`

func (q *Queries) ListNisaContributions(ctx context.Context) ([]NisaContribution, error) {
	rows, err := q.db.QueryContext(ctx, listNisaContributions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NisaContribution
	for rows.Next() {
		var i NisaContribution
		if err := rows.Scan(
			&i.ID,
			&i.ContributionDate,
			&i.Amount,
			&i.FundID,
			&i.ContributionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNisaContributionsByFund = `-- name: ListNisaContributionsByFund :many
SELECT id, contribution_date, amount, fund_id, contribution_type FROM nisa_contributions WHERE fund_id = ? ORDER BY contribution_date
`

func (q *Queries) ListNisaContributionsByFund(ctx context.Context, fundID int64) ([]NisaContribution, error) {
	rows, err := q.db.QueryContext(ctx, listNisaContributionsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NisaContribution
	for rows.Next() {
		var i NisaContribution
		if err := rows.Scan(
			&i.ID,
			&i.ContributionDate,
			&i.Amount,
			&i.FundID,
			&i.ContributionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenarios = `-- name: ListScenarios :many
SELECT id, run_at, params FROM scenarios ORDER BY run_at DESC LIMIT ?
`

func (q *Queries) ListScenarios(ctx context.Context, limit int64) ([]Scenario, error) {
	rows, err := q.db.QueryContext(ctx, listScenarios, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scenario
	for rows.Next() {
		var i Scenario
		if err := rows.Scan(&i.ID, &i.RunAt, &i.Params); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBigPurchase = `-- name: UpdateBigPurchase :one
UPDATE big_purchases
SET name = ?, base_amount = ?, base_date = ?, cycle_years = ?,
    trade_in_value = ?, recurring = ?, financing_mode = ?
WHERE id = ?
RETURNING id, name, base_amount, base_date, cycle_years, category_growth_rate, trade_in_value, recurring, financing_mode
`

type UpdateBigPurchaseParams struct {
	Name          string
	BaseAmount    int64
	BaseDate      time.Time
	CycleYears    int64
	TradeInValue  int64
	Recurring     bool
	FinancingMode string
	ID            int64
}

func (q *Queries) UpdateBigPurchase(ctx context.Context, arg UpdateBigPurchaseParams) (BigPurchase, error) {
	row := q.db.QueryRowContext(ctx, updateBigPurchase,
		arg.Name,
		arg.BaseAmount,
		arg.BaseDate,
		arg.CycleYears,
		arg.TradeInValue,
		arg.Recurring,
		arg.FinancingMode,
		arg.ID,
	)
	var i BigPurchase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseAmount,
		&i.BaseDate,
		&i.CycleYears,
		&i.CategoryGrowthRate,
		&i.TradeInValue,
		&i.Recurring,
		&i.FinancingMode,
	)
	return i, err
}

const updateBigPurchaseGrowthRate = `-- name: UpdateBigPurchaseGrowthRate :one
UPDATE big_purchases
SET category_growth_rate = ?
WHERE id = ?
RETURNING id, name, base_amount, base_date, cycle_years, category_growth_rate, trade_in_value, recurring, financing_mode
`

type UpdateBigPurchaseGrowthRateParams struct {
	CategoryGrowthRate sql.NullFloat64
	ID                 int64
}

func (q *Queries) UpdateBigPurchaseGrowthRate(ctx context.Context, arg UpdateBigPurchaseGrowthRateParams) (BigPurchase, error) {
	row := q.db.QueryRowContext(ctx, updateBigPurchaseGrowthRate, arg.CategoryGrowthRate, arg.ID)
	var i BigPurchase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseAmount,
		&i.BaseDate,
		&i.CycleYears,
		&i.CategoryGrowthRate,
		&i.TradeInValue,
		&i.Recurring,
		&i.FinancingMode,
	)
	return i, err
}

const updateExpenseForecastOverride = `-- name: UpdateExpenseForecastOverride :one
UPDATE expense_forecasts
SET annual_cost = ?, is_override = true
WHERE id = ?
RETURNING id, family_member_id, stage, track, annual_cost, start_age, end_age, is_override
`

type UpdateExpenseForecastOverrideParams struct {
	AnnualCost int64
	ID         int64
}

func (q *Queries) UpdateExpenseForecastOverride(ctx context.Context, arg UpdateExpenseForecastOverrideParams) (ExpenseForecast, error) {
	row := q.db.QueryRowContext(ctx, updateExpenseForecastOverride, arg.AnnualCost, arg.ID)
	var i ExpenseForecast
	err := row.Scan(
		&i.ID,
		&i.FamilyMemberID,
		&i.Stage,
		&i.Track,
		&i.AnnualCost,
		&i.StartAge,
		&i.EndAge,
		&i.IsOverride,
	)
	return i, err
}

const upsertFundNavHistory = `-- name: UpsertFundNavHistory :one

INSERT INTO fund_nav_history (fund_id, nav_date, nav_price)
VALUES (?, ?, ?)
ON CONFLICT (fund_id, nav_date) DO UPDATE SET nav_price = EXCLUDED.nav_price
RETURNING id, fund_id, nav_date, nav_price
`

type UpsertFundNavHistoryParams struct {
	FundID   int64
	NavDate  time.Time
	NavPrice int64
}

// fund_nav_history -----------------------------------------------------------
func (q *Queries) UpsertFundNavHistory(ctx context.Context, arg UpsertFundNavHistoryParams) (FundNavHistory, error) {
	row := q.db.QueryRowContext(ctx, upsertFundNavHistory, arg.FundID, arg.NavDate, arg.NavPrice)
	var i FundNavHistory
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.NavDate,
		&i.NavPrice,
	)
	return i, err
}

const upsertMonthlyRecord = `-- name: UpsertMonthlyRecord :one


INSERT INTO monthly_records (record_month, income_monthly, bank_balance)
VALUES (?, ?, ?)
ON CONFLICT (record_month)
DO UPDATE SET income_monthly = EXCLUDED.income_monthly, bank_balance = EXCLUDED.bank_balance
RETURNING id, record_month, income_monthly, bank_balance, created_at
`

type UpsertMonthlyRecordParams struct {
	RecordMonth   time.Time
	IncomeMonthly int64
	BankBalance   int64
}

// Queries are added here alongside schema.sql as each table is implemented.
// monthly_records --------------------------------------------------------
func (q *Queries) UpsertMonthlyRecord(ctx context.Context, arg UpsertMonthlyRecordParams) (MonthlyRecord, error) {
	row := q.db.QueryRowContext(ctx, upsertMonthlyRecord, arg.RecordMonth, arg.IncomeMonthly, arg.BankBalance)
	var i MonthlyRecord
	err := row.Scan(
		&i.ID,
		&i.RecordMonth,
		&i.IncomeMonthly,
		&i.BankBalance,
		&i.CreatedAt,
	)
	return i, err
}
